### PR TITLE
Refactor integration test logic.

### PR DESCRIPTION
**Pull request by jmyounker**
All integration tests I've contemplated have the same sets of operations.  I've pulled these out, so we can now write additional tests simply while only focusing on the important details in the test structure.

### CODE REVIEW

**Comment by jmyounker** [comment]
@peterbourgon @stuartnelson3 Ready for review

**Comment by peterbourgon** [comment]
-1 on principle. A given integration test should be wholly self-contained. We can worry about DRY optimizations once the suite gets a lot bigger.

It's perhaps out of scope of this PR but I'm also not at all happy with the way the integration tests have evolved. Specifically, the amount of ceremony encoded by `run.sh`, and the idea that one directory contains multiple independent tests that must be invoked by a carefully-stitched `go test` invocation. The original goal was to make integration tests exactly as difficult as `cd _integration/foo/bar && go test` and I'd like to see every PR be a step back toward that goal.

**Comment by jmyounker** [comment]
I don't know where you're getting the idea that this is about a small optimization.  These changes are essentially back-propagated from my next PR.  I made them because the subsequent integration tests were 80+% the same and all the boilerplate obscured their intentions.

Here are the next eight integration-tests:

func TestNoRestartNormalExit(t *testing.T) {
	cf := newContainerFixture(t, "finished-job-does-not-restart(restart=no)")
	cf.config.Command.Exec = []string{"bin/warhead", "-batch-mode", "-run-time", "1s", "-exit-code", "0"}

	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	// Container should finish
	wc := cf.wait(5 * time.Second, agent.ContainerStatusFinished)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not exit with state Finished")
	}
	cf.destroy()
}

func TestNoRestartAbnormalExit(t *testing.T) {
	cf := newContainerFixture(t, "failed-job-does-not-restart(restart=no)")
	cf.config.Command.Exec = []string{"bin/warhead", "-batch-mode", "-run-time", "1s", "-exit-code", "1"}

	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	// Container should finish
	wc := cf.wait(5 * time.Second, agent.ContainerStatusFailed)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not exit with state Failed")
	}
	cf.destroy()
}

func TestAlwaysRestartDoesNotAffectStoppedJobs(t *testing.T) {
	cf := newContainerFixture(t, "stopped-job-does-not-restart(restart=always)")
	cf.config.Restart = agent.AlwaysRestart

	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	cf.stop(agent.ContainerStatusFinsihed)
	// Container should not restart
	wc := cf.wait(5 * time.Second, agent.ContainerStatusRunning)
	w := <- wc
	if w.Err == nil {
		t.Fatal("Container should not have been restarted")
	}
	cf.destroy()
}

func TestAlwaysRestartWithFinishedJobRestarts(t * testing.T) {
	cf := newContainerFixture(t, "finished-job-restarts(restart=always)")
	cf.config.Command.Exec = []string{"bin/warhead", "-batch-mode", "-run-time", "1s", "-exit-code", "1"}
	cf.config.Restart = agent.AlwaysRestart

	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	// Container should fail
	wc := cf.wait(5 * time.Second, agent.ContainerStatusFinished)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not exit with state Finished")
	}
	// Container should restart
	wc := cf.wait(5 * time.Second, agent.ContainerStatusRunning)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not restart")
	}

	cf.stop(agent.ContainerStatusFinished)
	cf.destroy()
}

func TestAlwaysRestartWithFailedJobRestarts(t * testing.T) {
	cf := newContainerFixture(t, "failed-job-restarts(restart=always")
	cf.config.Command.Exec = []string{"bin/warhead", "-batch-mode", "-run-time", "1s", "-exit-code", "0"}
	cf.config.Restart = agent.AlwaysRestart

	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	// Container should fail
	wc := cf.wait(5 * time.Second, agent.ContainerStatusFailed)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not exit with state Failed")
	}
	// Container should restart
	wc := cf.wait(5 * time.Second, agent.ContainerStatusRunning)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not restart")
	}

	cf.stop(agent.ContainerStatusFinished)
	cf.destroy()
}

func TestOnFailureRestartDoesNotAffectStoppedJobs(t *testing.T) {
	cf := newContainerFixture(t, "stopped-job-does-not-restart(restart=on-failure)")
	cf.config.Restart = agent.OnFailureRestart
	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	cf.stop(agent.ContainerStatusFinsihed)
	// Container should not restart
	wc := cf.wait(5 * time.Second, agent.ContainerStatusRunning)
	w := <- wc
	if w.Err == nil {
		t.Fatal("Container should not have been restarted")
	}
	// If this were restarting then destroy would not work.
	cf.destroy()
}

func TestOnFailureRestartWithFinishedJobRestarts(t * testing.T) {
	cf := newContainerFixture(t, "finished-job-does-not-restart(restart=on-finished")
	cf.config.Command.Exec = []string{"bin/warhead", "-batch-mode", "-run-time", "1s", "-exit-code", "0"}
	cf.config.Restart = agent.OnFailureRestart

	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	// Container should fail
	wc := cf.wait(5 * time.Second, agent.ContainerStatusFinished)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not exit with state Finished")
	}
	// If this were restarting then destroy would not work.
	cf.destroy()
}

func TestOnFailureRestartWithFailedJobRestarts(t * testing.T) {
	cf := newContainerFixture(t, "failed-job-restarts(restart=on-failure")
	cf.config.Command.Exec = []string{"bin/warhead", "-batch-mode", "-run-time", "1s", "-exit-code", "1"}
	cf.config.Restart = agent.OnFailureRestart
	cf.create(agent.ContainerStatusCreated)
	cf.start(agent.ContainerStatusRunning)
	// Container should fail
	wc := cf.wait(5 * time.Second, agent.ContainerStatusFailed)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not exit with state Failed")
	}
	// Container should restart
	wc := cf.wait(5 * time.Second, agent.ContainerStatusRunning)
	w := <- wc
	if w.Err != nil {
		t.Fatal("Container did not restart")
	}

	cf.stop(agent.ContainerStatusFinished)
	cf.destroy()
}

**Comment by peterbourgon** [comment]
Okay. Thanks for the context. But I'm not seeing how that addresses any of my points of contention.

**Comment by peterbourgon** [comment]
To be a bit more concrete, I'd be +1 on this refactoring if

- The integration tests were one per directory
- The common code was a separate package, imported using standard Go import mechanisms
- The tests were invoked on a package, rather than file, level, i.e. `go test .` rather than `go test testfile.go sharedutil.go`
- The change didn't give the `run.sh` script any more responsibility, bearing in mind we should aim to remove it altogether long-term

**Comment by jmyounker** [comment]
I addressed what I perceived as the primary point that it's just a pointless DRY change.  It's a change that's already saved me hundreds of lines of pointless boiler point that obfuscates what the tests do.

I figured we talk more tomorrow since a detailed reply was going to take a while to write, and I wanted to continue actually gutting the agent and supervisor.

I think these responses address your points:

* From my point of view, nothing has evolved with the integration tests. All the work done in run.sh to date has been learning what we need to do to make any integration tests function *at all*. Until the last integ test PR we had something that only gave the appearances of being integration tests.  You couldn't create or destroy a container using the API and you couldn't do anything that involved signals.  (No stopping and no reporting of statuses changes by the supervisor.)  Nor could you reasonably debug the test if anything went wrong.

* I'm not concerned about the current state of invocation because I see a clear path ahead. The contents of run.sh eventually get migrated into Go as a struct and a set of methods that perform startup and shutdown of the test machinery, and those get called by the integration tests themselves.  I'm looking forward to testing.TestMain in go 1.4.

* Right now it seems to me that getting a working harness and means of quickly writing integration tests so that I can move forward with fixing the agent and supervisor are more important than the precise details of how the tests are being called.

I'm really tired of working on the harnessing, but it's been necessary to have something that works at all, and it looks like we *finally* have that.  Please appreciate what a nightmare this has been.

**Comment by peterbourgon** [comment]
I defer to your nightmare :)

:dango:

**Comment by jmyounker** [comment]
Closed in merge commit.

**Pull request closed without merging**
